from __future__ import annotations

import base64
import json
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from adbygod_api.core.reports import (
    REPORT_SECTION_CATALOG,
    build_report_payload,
    build_report_preview,
    render_csv_report,
    render_html_report,
    render_pdf_report,
)
from adbygod_api.core.reports.report_builder import sanitize_filename_component
from adbygod_api.database import get_db
from adbygod_api.models import PlatformUser
from adbygod_api.routes.auth import get_current_user

router = APIRouter(prefix="/reports", tags=["reports"])


class ReportExportRequest(BaseModel):
    assessment_id: UUID
    format: str = Field("json", pattern="^(json|csv|html|pdf)$")
    sections: list[str] = Field(default_factory=list)


class TechniqueExportRequest(BaseModel):
    technique_id: str
    title: str | None = None
    mitre_id: str | None = None
    risk_level: str | None = None
    description: str | None = None


def _render_report(payload: dict[str, Any], fmt: str) -> tuple[str | bytes, str, str]:
    normalized = fmt.lower().strip()
    if normalized == "json":
        return json.dumps(payload, indent=2, ensure_ascii=True, default=str), "application/json", "utf-8"
    if normalized == "csv":
        return render_csv_report(payload), "text/csv", "utf-8"
    if normalized == "html":
        return render_html_report(payload), "text/html", "utf-8"
    if normalized == "pdf":
        return render_pdf_report(payload), "application/pdf", "binary"
    raise HTTPException(status_code=400, detail="Unsupported report format")


def _base_filename(payload: dict[str, Any], assessment_id: UUID) -> str:
    assessment = payload.get("assessment", {})
    domain = sanitize_filename_component(str(assessment.get("domain") or "assessment"))
    name = sanitize_filename_component(str(assessment.get("name") or "report"), fallback="report")
    return f"adbygod-{domain}-{name}-{assessment_id}"


@router.get("/capabilities")
async def report_capabilities() -> dict[str, Any]:
    return {
        "formats": [
            {"id": "pdf", "label": "PDF Dossier", "media_type": "application/pdf", "binary": True},
            {"id": "html", "label": "HTML Briefing", "media_type": "text/html", "binary": False},
            {"id": "json", "label": "JSON Evidence Pack", "media_type": "application/json", "binary": False},
            {"id": "csv", "label": "CSV Finding Register", "media_type": "text/csv", "binary": False},
        ],
        "sections": list(REPORT_SECTION_CATALOG),
        "safety": {
            "provenance_labeled": True,
            "redacts_sensitive_evidence_values": True,
            "loot_values_omitted_from_reports": True,
        },
        "assurance": {
            "finding_payload_reconciliation": True,
            "coverage_gap_visibility": True,
            "risk_theme_clustering": True,
            "priority_action_board": True,
            "report_readiness_scoring": True,
        },
    }


@router.get("/preview/{assessment_id}")
async def preview_report(
    assessment_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: PlatformUser = Depends(get_current_user),
):
    return await build_report_preview(assessment_id, db, current_user)


@router.post("/export")
async def export_report(
    request: ReportExportRequest,
    db: AsyncSession = Depends(get_db),
    current_user: PlatformUser = Depends(get_current_user),
):
    payload = await build_report_payload(request.assessment_id, db, current_user, request.sections)
    content, mime_type, encoding = _render_report(payload, request.format)
    filename = f"{_base_filename(payload, request.assessment_id)}.{request.format}"

    if isinstance(content, bytes):
        serialized_content = base64.b64encode(content).decode("ascii")
        content_encoding = "base64"
        byte_length = len(content)
    else:
        serialized_content = content
        content_encoding = encoding
        byte_length = len(content.encode("utf-8"))

    return {
        "filename": filename,
        "mime_type": mime_type,
        "content": serialized_content,
        "content_encoding": content_encoding,
        "byte_length": byte_length,
        "payload": payload,
    }


@router.post("/export-technique")
async def export_technique_note(
    request: TechniqueExportRequest,
    current_user: PlatformUser = Depends(get_current_user),
):
    """Accept command-deck technique export events from older UI cards.

    Full assessment reports are generated by `/reports/export`; this endpoint
    keeps standalone technique cards from failing when they record an export
    action outside an assessment report context.
    """
    return {
        "status": "accepted",
        "technique_id": request.technique_id,
        "title": request.title,
        "mitre_id": request.mitre_id,
    }


@router.post("/export/file")
async def export_report_file(
    request: ReportExportRequest,
    db: AsyncSession = Depends(get_db),
    current_user: PlatformUser = Depends(get_current_user),
) -> Response:
    """Return a direct downloadable report body.

    `/reports/export` keeps the existing JSON-wrapped export contract used by the
    web client. This endpoint exists for CLI/API callers that prefer a true file
    response and for future browser streaming flows.
    """
    payload = await build_report_payload(request.assessment_id, db, current_user, request.sections)
    content, mime_type, _encoding = _render_report(payload, request.format)
    filename = f"{_base_filename(payload, request.assessment_id)}.{request.format}"
    raw = content if isinstance(content, bytes) else content.encode("utf-8")
    return Response(
        content=raw,
        media_type=mime_type,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-AdByG0d-Report-Sections": ",".join(payload.get("report_meta", {}).get("sections", {}).get("included", [])),
        },
    )
